Description: >
  This template deploys a basic IAM role with an Instance Profile

Parameters:
    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

Resources:


    ESRole:
        Type: 'AWS::IAM::ServiceLinkedRole'
        Properties:
            AWSServiceName: es.amazonaws.com
            Description: 'Role for ES to access resources in my VPC'


    ECSRole:
        Type: AWS::IAM::Role
        Properties:
            ManagedPolicyArns: 
                - "arn:aws:iam::aws:policy/CloudWatchFullAccess"
                - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
                - "arn:aws:iam::aws:policy/AmazonECS_FullAccess"
                - "arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role"
                - "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess"
            RoleName: ecsInstanceRole
            AssumeRolePolicyDocument: |
                {
                    "Statement": [{
                        "Action": "sts:AssumeRole",
                        "Effect": "Allow",
                        "Principal": {
                            "Service": "ec2.amazonaws.com"
                        }
                    }]
                }


    ECSInstanceProfile:
        Type: AWS::IAM::InstanceProfile
        Properties:
            Path: /
            Roles:
                - !Ref ECSRole




Outputs:
    ECSRole:
        Description: A reference to IAM Role
        Value: !Ref ECSRole
    ECSInstanceProfile:
        Description: A reference to IAM Profile
        Value: !Ref ECSInstanceProfile
    ESRole:
        Value: !Ref ESRole

